### ISSUE TITLE
Source code line endings

### ISSUE THREAD

**Issue by hardyx** [gameblabla/evilaustralians#1]
Some source files in WRAPPER folder have incorrect line endindgs (^M). You can set core.autocrlf=true in file .gitconfig to make git convert line endings correctly.

**Comment by gameblabla** [comment]
Sorry for taking so long lol.
And no, i'm not going to switch to CRLF line endings.
I mainly work on Linux and i don't want to deal with that kludge.

Even Notepad++ supports most line endings out there.
So sorry, it will be a no.
